export enum CurrencyCodes {
  CANADIAN_DOLLAR = 'CAD',
  UNITED_STATES_DOLLAR = 'USD',
  EURO = 'EUR',
  BRITISH_POUND = 'GBP',
  AUSTRALIAN_DOLLAR = 'AUD',
  JAPANESE_YEN = 'JPY',
  CHINESE_YUAN = 'CNY',
  INDIAN_RUPEE = 'INR',
  MEXICAN_PESO = 'MXN',
  NEW_ZEALAND_DOLLAR = 'NZD'
}
